### ISSUE TITLE
CrashPlayer stuck on loading

### ISSUE THREAD

**Issue by QuinDennis** [crashbob/CRASHPlayer#7]
I've used the app for a couple of years, but recently it stopped working, it gets stuck at "loading". I just got the latest copy, it behaves the same. Vizio E320i-A0 ... (just this morning there was a store update, but CrashPlayer still won't load)

**Comment by rioniac** [comment]
Did you recently upgrade your Plex server software/hardware?  CrashPlayer is working fine on my Vizio E470i-A0.

**Comment by QuinDennis** [comment]
Yes, there was a server update which I applied.  In trouble-shooting I
loaded a previous server version but the problem persist.

**Comment by QuinDennis** [comment]
Hi, I did upgrade the software.  What Plex server version are you using, 
I should install that.

On 01/13/2016 08:31 PM, Sebastian Courtney wrote:

> Did you recently upgrade your Plex server software/hardware? 
> CrashPlayer is working fine on my Vizio E470i-A0.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/crashbob/CRASHPlayer/issues/7#issuecomment-171511869.

## 

Quin Dennis | t: 512.392.8619 | c: 512.214.3193
